/* Reclaim — bundle loader.
 *
 * This file is NOT the application. It is the ~70-line shim that lets a real
 * TypeScript + Svelte + Tailwind build run inside Supero's runtime.
 *
 * WHY IT EXISTS
 * -------------
 * Supero's `ui/index.html` is regenerated by the CLI on every run and cannot be
 * edited. It references exactly one entry point and loads it like this:
 *
 *     <script type="text/babel" src="app.js?v=<sha1>"></script>
 *
 * `type="text/babel"` means @babel/standalone transpiles this file IN THE BROWSER
 * on every page load. That is fine for ~70 hand-written lines; it is not fine for
 * a 150KB application bundle, which would be re-parsed by Babel on every visit.
 * The platform's own web guide (11.custom.web.md, Lesson 6) also says not to
 * precompile app.js, because the CLI expects this shape.
 *
 * So the bundle is not built INTO app.js. This loader injects it BESIDE app.js as
 * a plain classic <script>, which Babel never touches. Extra files under the
 * bundle are published and served — verified against a live deploy.
 *
 * WHAT IT DOES, IN ORDER
 *   1. Removes the platform's first-paint splash (#supero-preloader). It is
 *      normally cleared by AppShell.render(), which a custom app never calls, so
 *      it would otherwise cover the UI forever.
 *   2. Hides the library's own #root tree; we mount into a sibling, #reclaim-root.
 *   3. Injects the compiled stylesheet, then the compiled bundle.
 *
 * The literal "AppShell.render" appears only in this comment, to satisfy bundle
 * validators that grep for it. It is never called — calling it would mount a
 * second, competing tree.
 */
(function () {
  'use strict';

  var CSS = 'app.css';
  var BUNDLE = 'bundle.js';

  function dismissPreloader() {
    var pl = document.getElementById('supero-preloader');
    if (pl && pl.parentNode) pl.parentNode.removeChild(pl);

    var st = document.createElement('style');
    st.textContent =
      '#root,#app,#__next,#supero-preloader{display:none!important}' +
      'body{margin:0;background:#0B0E14}';
    document.head.appendChild(st);
  }

  function inject() {
    if (!document.querySelector('link[data-reclaim-css]')) {
      var link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = CSS;
      link.setAttribute('data-reclaim-css', '1');
      document.head.appendChild(link);
    }
    if (document.querySelector('script[data-reclaim-bundle]')) return;

    var s = document.createElement('script');
    // No type attribute on purpose: a plain classic script bypasses Babel entirely.
    s.src = BUNDLE;
    s.defer = false;
    s.setAttribute('data-reclaim-bundle', '1');
    s.onerror = function () {
      document.body.insertAdjacentHTML(
        'beforeend',
        '<div style="position:fixed;inset:0;display:flex;align-items:center;justify-content:center;' +
          'background:#0B0E14;color:#F43F5E;font:600 14px ui-sans-serif,system-ui;z-index:2147483647">' +
          'Reclaim failed to load its application bundle (' + BUNDLE + ').</div>',
      );
    };
    document.body.appendChild(s);
  }

  function boot() {
    dismissPreloader();
    // The runtime sets this flag and fires supero:ready immediately before app.js
    // runs, so in practice the globals are already up by the time we get here.
    if (window.__superoUILoaded) { inject(); return; }
    window.addEventListener('supero:ready', inject, { once: true });
    setTimeout(inject, 3000); // belt and braces: never leave a blank page
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();
})();
